### ISSUE TITLE
install the bin command as anything besides serve, maybe 'sserve'

### ISSUE THREAD

**Issue by hqtsky** [daquinoaldo/https-localhost#27] opened 2019-09-17 21:34 UTC
**How would you like to expand the functionalities?**
This module replaces another npm called 'serve' when installed globally: https://www.npmjs.com/package/serve

It would be nice to install this under 'sserve' or something alternative so we can have access to both.

**Are there alternatives?**
Manually rename the link and relink the 'serve'.

**Is it a breaking change?**
This is not a breaking change. Users can run it using a different command, which that is after install.

**Comment by daquinoaldo** [comment] 2019-09-18 15:46
I could manage it, but it will change the way users run it. It's kinda a breaking change.
Let me think about that, there are other things I would like to implement that are breaking change too, I can include that one in v5.0.0.
Anyway, I'm pretty busy with the University stuff, I don't know when I'll implement that, could be in a week as in the Christmas holidays...

**Comment by daquinoaldo** [comment] 2019-10-01 12:39
I've discussed your feature request with some friends and I decided to switch to the `sserve` command as you suggest.
I started thinking about v5.0.0 implementation. Hopefully, it will be published before Christmas.

**Comment by daquinoaldo** [comment] 2019-10-17 07:18
Confirmed in v5.0.0. I'll close the issue since I consider it resolved. Just wait for a stable (or a beta) v5.0.0.

**Closed by daquinoaldo** 2019-10-17 07:18 UTC
Labels: feature
