### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by leonardop21** [daquinoaldo/https-localhost#14] opened 2019-04-26 12:19 UTC
Hello,

I am starting the server on port 4433 as an example and pointing to the path of my project, but when accessed by the browser, I get an error of not found. What can I do wrong?

Running the local server without https the site works normally

1 ![Captura de Tela 2019-04-26 às 09 17 24](https://user-images.githubusercontent.com/17708447/56807195-7e526e00-6804-11e9-8347-b56a16c0789d.png)

2 ![Captura de Tela 2019-04-26 às 09 18 08](https://user-images.githubusercontent.com/17708447/56807196-7e526e00-6804-11e9-8a4d-87e7e4c25ba5.png)

**Comment by daquinoaldo** [comment] 2019-04-26 12:26
I know that is a stupid question, but: there is an index file in that folder? If you try to append an existent file you got the same error? Like: https://localhost:4443/file.html

**Comment by leonardop21** [comment] 2019-04-26 14:03
Yes, I created a part folder with an index.html and tried to access, the same error occurred

**Comment by daquinoaldo** [comment] 2019-04-29 10:52
I've tried to reproduce this error, without any success. I followed these steps.

1. Uninstall https-localhost with `npm -g uninstall https-localhost`. `which serve` shouldn't print anything.
2. Install https-localhost with `npm i -g --only=prod https-localhost`.
3. `mkdir test` and `echo "<html><body>TEST</body></html>" > test/index.html`.
4. `PORT=4443 serve test`. You should see "TEST" on https://localhost:4443.

I'm using macOS Mojave latest version (10.14.4), Node.js v11.14.0 and npm v6.9.0.
Can you please provide your system data?

It seems not to be a problem related to the certificate, but something related to express.js or path resolving.

**Comment by leonardop21** [comment] 2019-05-03 21:05
Hello,
Sorry for the delay, follow the tutorial above and I encountered the same problem. I tested with direct test and then passing the complete path of the directory where the file was, as print below. I will repeat the test at home with a windows pc.

![Captura de Tela 2019-05-03 às 18 04 01](https://user-images.githubusercontent.com/17708447/57165605-fead3c00-6dcd-11e9-9829-a1e9d019fafd.png)
![Captura de Tela 2019-05-03 às 18 04 12](https://user-images.githubusercontent.com/17708447/57165606-ff45d280-6dcd-11e9-8bf8-cac3471ef982.png)
![Captura de Tela 2019-05-03 às 18 04 18](https://user-images.githubusercontent.com/17708447/57165607-ff45d280-6dcd-11e9-8c32-7b8f59bc8376.png)

**Comment by daquinoaldo** [comment] 2019-05-03 21:41
Could you please try to clone the repository and perform `npm test`?

**Comment by leonardop21** [comment] 2019-05-06 17:18
Would it be this?

![Captura de Tela 2019-05-06 às 14 17 53](https://user-images.githubusercontent.com/17708447/57242424-d6118600-7009-11e9-8974-1300e2b34171.png)

**Comment by daquinoaldo** [comment] 2019-05-06 17:35
No, this error is because you have not install the dev requirements, you can install them with `npm install` without the `--only=prod` option. Then you should be able to run tests.

**Comment by leonardop21** [comment] 2019-05-06 18:33
It looks like all the tests have been completed successfully. Could it be some other program on my machine that is causing conflict?


Testing certs
    ✓ can be uninstalled
    ✓ uninstall is idempotent (doesn't fail if called twice)
Generating certificates...
Downloading the mkcert executable...
Running mkcert to generate certificates...
Certificates generated, installed and trusted. Ready to go!
    ✓ can be installed (19274ms)
Generating certificates...
Downloading the mkcert executable...
Running mkcert to generate certificates...
Certificates generated, installed and trusted. Ready to go!
Server running on port 4443.
    ✓ can be installed at first run (9300ms)
Cannot find localhost.key and localhost.crt in the specified path: does-not-exist
Server running on port 4443.
    ✓ crashes if certs doesn't exists in custom folder

  Testing module
Server running on port 4443.
    ✓ works as express app
Server running on port 4443.
    ✓ works with environment port

  Testing serve
Serving static path: test
Server running on port 4443.
    ✓ serves static files from custom path (55ms)
Serving static path: test
Server running on port 4443.
    ✓ serves static files from default env port
Serving static path: /Users/wwwjsw/Desktop/leonardo/test/https-localhost
Server running on port 4443.
    ✓ doesn't crash on 404 (256ms)
Serving static path: test
Server running on port 4443.
    ✓ looks for a 404.html file
Serving static path: does-not-exist
Server running on port 4443.
    ✓ doesn't crash if the static path doesn't exists

  Testing additional features
http to https redirection active.
    ✓ redirect http to https
Serving static path: test
Server running on port 4443.
    ✓ is ready for production (1441ms)


  14 passing (31s)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 certs.js |      100 |      100 |      100 |      100 |                   |
 index.js |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|

> https-localhost@4.1.0 posttest /Users/wwwjsw/Desktop/leonardo/test/https-localhost
> node node_modules/nyc/bin/nyc.js report --reporter=html

**Comment by daquinoaldo** [comment] 2019-05-06 18:39
Yes, them have been completed successfully. That is pretty strange, because there are tests with a file served on port 4443 and seem to work.
I do not exclude that could be a conflict with other programs. Any ideas?
Can you please try to run it with sudo permissions?
Have you tried it on Windows?
Thank you for your patience and your cooperation!

**Comment by leonardop21** [comment] 2019-05-06 18:51
I do not know if I can test today, but during the week I'm going to do new tests here on mac and windows, and I bring new feedback

**Comment by daquinoaldo** [comment] 2019-05-06 18:55
Thank you very much!

**Comment by daquinoaldo** [comment] 2019-05-13 20:26
@leonardop21 any news?

**Comment by daquinoaldo** [comment] 2019-05-16 19:49
Feel free to open it again if you have any further information. Thank you for your help.

**Closed** 2019-05-16 19:48 UTC
Labels: bug, help wanted
